CREATE TABLE Writer
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    age  int CHECK (age > 0)
);

CREATE TABLE Book
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    year int CHECK (year < 2023)
);

CREATE TABLE Writer_Book
(
    writer_id int REFERENCES Writer (id),
    book_id   int REFERENCES Book (id),
    PRIMARY KEY (writer_id, book_id)
);