create table if not exists Person
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  varchar(100) not null unique,
    birth_year int          not null check ( birth_year > 0 )
);

create table if not exists Book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int          NOT NULL REFERENCES Person (id),
    name      varchar(100) not null,
    author    varchar(100) not null,
    year      int          not null check ( year > 0 )
);


